theme: jekyll-theme-minimal
title: <img src="https://github.com/Mateoswiatek/mateoswiatek.github.io/blob/b2a3b898f6c9872e7b9a72d833148ebcca9b7b34/Profilowe.png" width="200" height="250"> <br />Mateusz Świątek CV
description: Dziwne, u mnie działa
