remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mateusz Świątek CV <img src="https://user-images.githubusercontent.com/115046087/205402311-74a1391e-6d36-4072-9256-8413b1f06ba2.jpg" width="200" height="250"> <br />
description: Dziwne, u mnie działa, próbowaleś włączyć i wyłączyć?


