remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: <img src="https://github.com/Mateoswiatek/mateoswiatek.github.io/blob/main/agh%204.jpg" width="200" height="250"> <br /> CV Mateusz Świątek
description: Dziwne, u mnie działa, próbowaleś włączyć i wyłączyć?


